language: python
python:
  - "2.7"
language: node_js
node_js:
- 0.10
before_script:
  - chmod +x bin/JMeterInstaller.py
  - "npm install -g se-interpreter"
script:
  - nosetests -s
  - rm -rf results && mkdir results
  - apache-jmeter-2.13/bin/jmeter.sh -j results/jmeter.log -p tests/jmeter.properties -t tests/my_test_with_parameters.jmx -n -l results/my_test_with_parameters.jtl -Jserver=vzdispatchtest.azurewebsites.net
  - bin/generate_files_from_jtl.sh my_test_with_parameters
  - "se-interpreter interpreter_config.json"

env:
  global:
    - SAUCE_USERNAME=jackchem2003
    - SAUCE_ACCESS_KEY=3d4fa22d-12ad-4f18-9168-37ea7d88b522


